version: 0.1

env:
  parameter-store:
    SONAR_LOGIN: 4b10472faeabd02e136783eba7a052c02e0ff79a
    SONAR_HOST: http://ec2-3-87-142-74.compute-1.amazonaws.com

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST
      - mvn package
      
artifacts:
  files:
    - target/aws-build-sample-maven-project-0.0.1-SNAPSHOT.jar
    
    
